apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-cert
spec:
  secretName: app-secret
  issuerRef:
    name: letsencrypt-test
    kind: ClusterIssuer
  dnsNames:
  - microservice.easydevop.com 
   