apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: taiwolawal360@gmail.com
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
    - selector:
        dnsZones:
          - microservice.easydevop.com
          - argocd.microservice.easydevop.com
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z0435443313TMJNTM113I