apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: benita_lv@yahoo.com
    privateKeySecretRef:
      name: letsencrypt-test-key
    solvers:
    - selector:
        dnsZones:
          - test.bossladyb.online
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z0435443313TMJNTM113I