apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-test"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: "microservice.easydevop.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80

  # - host: "argocd.microservice.easydevop.com"
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: app-service
  #           port:
  #             number: 80
  tls:
  - hosts:
    - "microservice.easydevop.com"
    secretName: "app-secret"